services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - hamiltonian_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/config.env
    ports:
      - "5000:5002"
    networks:
      - hamiltonian_network

networks:
  hamiltonian_network:
    driver: bridge
